# ==============================================================================
# 02b_enrich_abandonment.R
#
# Enriches the abandonment risk set with dyadic covariates.
# Mirror of 02a_enrich_adoption.R for the abandonment flow.
#
# Input:  data/derived/all_events_abandonment.rds
#         data/derived/cog_lkp.rds            (generated by 02a_enrich_adoption.R)
#         data/raw/onet/db_15_1/
#         data/raw/bls/national_M2015_dl.xlsx
#         data/crosswalk/2010_to_2019_Crosswalk.csv
#
# Output: data/derived/all_events_abandonment_enriched.rds
#
# DIFFERENCES from 02a_enrich_adoption.R:
#   1. Input:   all_events_abandonment.rds  (outcome = abandonment)
#   2. cog_lkp: reused from disk (not recomputed)
#   3. DTC diagnostic: expected ratio is inverted
#      Cognitive: ratio < 1 (lower-status targets abandon more)
#      Physical:  ratio > 1 (higher-status targets abandon more)
#
# Intermediates: deleted before final save
# Next:          03_nestedness.R
# ==============================================================================

gc()
library(data.table)
library(readxl)

# ==============================================================================
# Paths
# ==============================================================================
if (file.exists("R/99_paths_local.R")) source("R/99_paths_local.R")

path_2015  <- if (exists("PATH_ONET_2015")) PATH_ONET_2015 else
              "data/raw/onet/db_15_1"
path_bls   <- if (exists("PATH_BLS_2015")) PATH_BLS_2015 else
              "data/raw/bls/national_M2015_dl.xlsx"
path_cw    <- "data/crosswalk/2010_to_2019_Crosswalk.csv"
out_dir    <- "data/derived"
input_file <- file.path(out_dir, "all_events_abandonment.rds")
cog_file   <- file.path(out_dir, "cog_lkp.rds")

stopifnot("Input not found — run 01b_risk_set_abandonment.R first" =
            file.exists(input_file))
stopifnot("cog_lkp.rds not found — run 02a_enrich_adoption.R first" =
            file.exists(cog_file))
stopifnot("O*NET 2015 not found" = dir.exists(path_2015))
stopifnot("BLS 2015 not found"   = file.exists(path_bls))
stopifnot("Crosswalk not found"  = file.exists(path_cw))
message("[OK] All inputs exist")

# ==============================================================================
# clean_id
# ==============================================================================
clean_id <- function(x) {
  s <- as.character(x)
  s <- gsub("-", "", s)
  s <- gsub("\\.[0-9]+$", "", s)
  trimws(s)
}
stopifnot(clean_id("15-1212.01") == "151212")
message("[OK] clean_id verified")

# ==============================================================================
# Step 1 — Load abandonment risk set
# ==============================================================================
message("\n>>> Step 1: Loading abandonment risk set...")

dt <- readRDS(input_file)
setDT(dt)

message(sprintf("  Rows:        %s", format(nrow(dt), big.mark = ",")))
message(sprintf("  Source occ:  %d", uniqueN(dt$source)))
message(sprintf("  Target occ:  %d", uniqueN(dt$target)))
message(sprintf("  Skills:      %d", uniqueN(dt$skill_name)))
message(sprintf("  Abandonment: %.4f", mean(dt$abandonment)))

occ_in_risk_set <- union(unique(dt$source), unique(dt$target))
domain_lkp <- unique(dt[, .(skill_name, domain)])
message("  Domains:")
print(domain_lkp[, .N, by = domain][order(-N)])
gc()

# ==============================================================================
# Step 2 — Wages (BLS OEWS 2015)
# ==============================================================================
message("\n>>> Step 2: BLS 2015 wages...")

bls <- as.data.table(read_excel(path_bls, sheet = 1))
setnames(bls, names(bls), toupper(names(bls)))
if ("OCC_GROUP" %in% names(bls))
  bls <- bls[OCC_GROUP == "detailed"]
bls[, soc_code := clean_id(OCC_CODE)]
bls[, wage := suppressWarnings(as.numeric(A_MEDIAN))]
bls <- bls[!is.na(wage) & nchar(soc_code) == 6]
wages <- bls[, .(wage = mean(wage, na.rm = TRUE)), by = soc_code]
wages[, log_wage := log(wage)]
message(sprintf("  BLS occupations: %d", nrow(wages)))
rm(bls); gc()

setkey(wages, soc_code)
dt[wages, on = .(source = soc_code),
   `:=`(s_wage = i.wage, log_s_wage = i.log_wage)]
dt[wages, on = .(target = soc_code),
   `:=`(t_wage = i.wage, log_t_wage = i.log_wage)]
rm(wages); gc()

dt[, wage_gap  := log_t_wage - log_s_wage]
dt[, wage_up   := pmax(0, wage_gap)]
dt[, wage_down := pmin(0, wage_gap)]
dt[, up_dummy  := fifelse(!is.na(wage_gap) & wage_gap > 0, 1L, 0L)]

pct_wage <- 100 * mean(!is.na(dt$wage_gap))
message(sprintf("  wage_gap coverage: %.1f%%", pct_wage))
if (pct_wage < 80)
  warning("wage_gap coverage < 80% — consistent with adoption pipeline")

# ==============================================================================
# Step 3 — Education (O*NET 2015, Scale RL)
# ==============================================================================
message("\n>>> Step 3: Education O*NET 2015 (Scale RL)...")

edu_file <- file.path(path_2015,
                      "Education, Training, and Experience.txt")
stopifnot(file.exists(edu_file))

edu_raw <- fread(edu_file, sep = "\t", quote = "",
                 na.strings = c("NA", "n/a", "", "*"),
                 showProgress = FALSE)
setnames(edu_raw, names(edu_raw), make.names(names(edu_raw)))
edu_raw <- edu_raw[
  Element.Name == "Required Level of Education" &
  Scale.ID == "RL"
]
edu_raw[, soc_code := clean_id(O.NET.SOC.Code)]
edu_raw[, cat := suppressWarnings(as.numeric(Category))]
edu_raw[, val := suppressWarnings(as.numeric(as.character(Data.Value)))]
edu_raw <- edu_raw[!is.na(cat) & !is.na(val) & val > 0]

cw_e <- unique(fread(path_cw)[, .(
  soc10 = clean_id(`O*NET-SOC 2010 Code`),
  soc19 = clean_id(`O*NET-SOC 2019 Code`)
)])
edu_raw <- merge(edu_raw, cw_e,
                 by.x = "soc_code", by.y = "soc10",
                 all.x = FALSE, allow.cartesian = TRUE)
edu_raw[, soc_code := soc19]
rm(cw_e)

edu <- edu_raw[, .(
  edu_expected = sum(cat * val, na.rm = TRUE) / sum(val, na.rm = TRUE)
), by = soc_code]
edu <- edu[!is.na(edu_expected)]
edu[, log_edu := log(edu_expected)]
rm(edu_raw); gc()

message(sprintf("  Occupations with edu: %d | median=%.2f",
                nrow(edu), median(edu$edu_expected)))

setkey(edu, soc_code)
dt[edu, on = .(source = soc_code),
   `:=`(s_edu = i.edu_expected, log_s_edu = i.log_edu)]
dt[edu, on = .(target = soc_code),
   `:=`(t_edu = i.edu_expected, log_t_edu = i.log_edu)]
rm(edu); gc()

dt[, edu_gap      := log_t_edu - log_s_edu]
dt[, edu_up       := pmax(0,  edu_gap)]
dt[, edu_down     := pmin(0,  edu_gap)]
dt[, edu_up_dummy := fifelse(!is.na(edu_gap) & edu_gap > 0, 1L, 0L)]

message(sprintf("  edu_gap coverage: %.1f%%",
                100 * mean(!is.na(dt$edu_gap))))

# ==============================================================================
# Step 4 — Cognitive score
# Reuses cog_lkp.rds generated by 02a_enrich_adoption.R.
# The socio-cognitive fraction is the same for both flows —
# it is an occupation-level property, not a flow-specific one.
# ==============================================================================
message("\n>>> Step 4: Cognitive score (from cog_lkp.rds)...")

cog_lkp <- readRDS(cog_file)
setDT(cog_lkp)
message(sprintf("  Occupations in cog_lkp: %d", nrow(cog_lkp)))
message(sprintf("  cog_score: mean=%.4f | range [%.4f, %.4f]",
                mean(cog_lkp$cog_score),
                min(cog_lkp$cog_score),
                max(cog_lkp$cog_score)))

setkey(cog_lkp, soc_code)
dt[cog_lkp, on = .(source = soc_code), s_cog := i.cog_score]
dt[cog_lkp, on = .(target = soc_code), t_cog := i.cog_score]
rm(cog_lkp); gc()

dt[, cog_gap      := t_cog - s_cog]
dt[, cog_up       := pmax(0,  cog_gap)]
dt[, cog_down     := pmin(0,  cog_gap)]
dt[, cog_up_dummy := fifelse(!is.na(cog_gap) & cog_gap > 0, 1L, 0L)]

message(sprintf("  cog_gap coverage: %.1f%%",
                100 * mean(!is.na(dt$cog_gap))))

# ==============================================================================
# Step 5 — Coverage checks
# ==============================================================================
message("\n>>> Step 5: Coverage checks...")

check_cov <- function(col, label, thr = 0.85) {
  pct <- mean(!is.na(dt[[col]]))
  status <- ifelse(pct >= thr, "[OK]", "[CHECK]")
  message(sprintf("  %s %-25s %.1f%%", status, label, 100 * pct))
}
check_cov("wage_gap",            "wage_gap",            thr = 0.75)
check_cov("edu_gap",             "edu_gap",             thr = 0.70)
check_cov("cog_gap",             "cog_gap",             thr = 0.75)
check_cov("structural_distance", "structural_distance")
stopifnot(sum(is.na(dt$structural_distance)) == 0)

# ==============================================================================
# Step 6 — DTC diagnostic for abandonment
# NOTE: logic is opposite to adoption
#   G_ij = status_j - status_i (target - source)
#   up_dummy = 1 if target j has higher status than source i
#
#   DTC predicts for abandonment:
#     Cognitive: lower-status targets abandon more
#                -> upward dyads (j > i) have LOWER abandonment rate
#                -> ratio upward/downward < 1
#     Physical:  higher-status targets abandon more
#                -> upward dyads (j > i) have HIGHER abandonment rate
#                -> ratio upward/downward > 1
# ==============================================================================
message("\n>>> Step 6: DTC diagnostic for abandonment...")

dt[, direction := fcase(
  wage_gap > 0,     "upward",
  wage_gap < 0,     "downward",
  !is.na(wage_gap), "lateral"
)]
tab <- dt[!is.na(direction) & direction != "lateral",
          .(n = .N, rate = mean(abandonment)),
          by = .(domain, direction)]
setorder(tab, domain, direction)
print(tab)

wide <- dcast(tab, domain ~ direction, value.var = "rate")
if (all(c("upward", "downward") %in% names(wide))) {
  wide[, ratio := round(upward / downward, 3)]
  message("  Ratio upward/downward:")
  print(wide)
  message("  Expected — Cognitive: ratio < 1 | Physical: ratio > 1")
}
dt[, direction := NULL]

# ==============================================================================
# Step 7 — Save and clean up
# ==============================================================================
message("\n>>> Step 7: Saving...")

message(sprintf("  Rows:    %s", format(nrow(dt), big.mark = ",")))
message(sprintf("  NAs wage_gap: %d | edu_gap: %d | cog_gap: %d",
                sum(is.na(dt$wage_gap)),
                sum(is.na(dt$edu_gap)),
                sum(is.na(dt$cog_gap))))

out_path <- file.path(out_dir, "all_events_abandonment_enriched.rds")
saveRDS(dt, out_path)
message(sprintf("  Saved: %s", out_path))
message(sprintf("  Size:  %.1f MB", file.size(out_path) / 1e6))

# Remove intermediate file
file.remove(file.path(out_dir, "all_events_abandonment.rds"))
message("  [OK] Removed: all_events_abandonment.rds")

rm(dt); gc()
message("\n>>> 02b_enrich_abandonment.R complete.")
message("    Next: 03_nestedness.R")
