# =============================================================================
# 10_export_manuscript_figures.R
# Copy pipeline-generated figures into the Overleaf manuscript figures/ folder.
#
# The manuscript (../draft/draft.tex) includes each figure via
#   \input{figures/<name>.tex}  ->  \includegraphics{figures/<name>.pdf}
# where figures/ is the Overleaf PROJECT-ROOT folder (one level above this
# replication repo). This script mirrors the canonical pipeline outputs from
# output/figures/{main,si}/ into that folder under the basenames the
# manuscript expects.
#
# Run from the replication repo root, AFTER the figure-producing scripts:
#   04_status_pca.R, 06_projections.R, 07_fig1_descriptive.R,
#   08_fig2_regression.R, and the SI_* figure scripts.
#
#   Rscript R/10_export_manuscript_figures.R
# =============================================================================

# ---- Paths -----------------------------------------------------------------
# Manuscript figures/ lives at the Overleaf project root, i.e. the parent of
# this replication repository. Override MANUSCRIPT_FIGS if your layout differs.
MANUSCRIPT_FIGS <- Sys.getenv("MANUSCRIPT_FIGS", unset = "../figures")
SRC_MAIN <- file.path("output", "figures", "main")
SRC_SI   <- file.path("output", "figures", "si")

dir.create(MANUSCRIPT_FIGS, showWarnings = FALSE, recursive = TRUE)

# ---- Source -> manuscript basename map -------------------------------------
# list(src_dir, src_file, dest_file). dest_file is the name draft.tex expects.
# NOTE: 07_fig1_descriptive.R writes the descriptives panel as
# 'fig1_full_networks.pdf'; the manuscript refers to it as
# 'fig1_descriptives.pdf', so we rename on copy.
fig_map <- list(
  list(SRC_MAIN, "fig1_full_networks.pdf",            "fig1_descriptives.pdf"),
  list(SRC_MAIN, "fig2_regression.pdf",               "fig2_regression.pdf"),
  list(SRC_MAIN, "fig3_unified.pdf",                  "fig3_unified.pdf"),
  list(SRC_MAIN, "fig_pca_status.pdf",                "fig_pca_status.pdf"),
  list(SRC_SI,   "fig_S2_cs_distribution.pdf",        "fig_S2_cs_distribution.pdf"),
  list(SRC_SI,   "fig_SI_test_iii.pdf",               "fig_SI_test_iii.pdf"),
  list(SRC_SI,   "fig_S1_rca_threshold.pdf",          "fig_S1_rca_threshold.pdf"),
  list(SRC_SI,   "fig_SI_alt_status_Adoption.pdf",    "fig_SI_alt_status_Adoption.pdf"),
  list(SRC_SI,   "fig_SI_alt_status_Abandonment.pdf", "fig_SI_alt_status_Abandonment.pdf"),
  list(SRC_SI,   "fig_archetype_misclassification.pdf","fig_archetype_misclassification.pdf"),
  list(SRC_SI,   "fig_SI_subsample_stability.pdf",    "fig_SI_subsample_stability.pdf"),
  list(SRC_SI,   "fig_SI_subperiods.pdf",             "fig_SI_subperiods.pdf")
)

n_ok <- 0L; n_missing <- 0L
for (m in fig_map) {
  src  <- file.path(m[[1]], m[[2]])
  dest <- file.path(MANUSCRIPT_FIGS, m[[3]])
  if (file.exists(src)) {
    file.copy(src, dest, overwrite = TRUE)
    message(sprintf("  copied %-38s -> figures/%s", m[[2]], m[[3]]))
    n_ok <- n_ok + 1L
  } else {
    warning(sprintf("  MISSING source: %s (manuscript needs figures/%s)",
                    src, m[[3]]), call. = FALSE)
    n_missing <- n_missing + 1L
  }
}

# ---- Notes on figures the pipeline does NOT produce ------------------------
# 1. figures/illustration.png  (Fig. 1, fig:diffusion-schematic) is a hand-made
#    conceptual schematic, not generated by any R script. Place it in
#    ../figures/ manually; it is not handled here.
# 2. fig_SI_alt_status_{Adoption,Abandonment}.pdf are two separate panels used
#    by the manuscript. The current SI_09_alternative_status.R writes a single
#    combined 'fig_SI_alt_status.pdf'. If the two split files are absent above,
#    regenerate them from SI_09 (or split the combined figure) before export.

if (!file.exists(file.path(MANUSCRIPT_FIGS, "illustration.png")))
  message("  NOTE: figures/illustration.png not present — add the hand-made ",
          "schematic manually (not pipeline-generated).")

message(sprintf("\nDone: %d figures exported to %s (%d missing).",
                n_ok, MANUSCRIPT_FIGS, n_missing))
